-- Add verification columns to ideas table
ALTER TABLE public.ideas 
ADD COLUMN IF NOT EXISTS ai_verified BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS ai_score INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS ai_predicted_price NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS ai_analysis TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;